parameters:
#    my_blog_admin_manage.example.class: MyBlog\Admin\ManageBundle\Example

services:
#    my_blog_admin_manage.example:
#        class: %my_blog_admin_manage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my_blog_admin_manage.admin.blog:
        class: MyBlog\Admin\ManageBundle\Admin\BlogAdmin
        arguments: [~, MyBlog\CoreBundle\Entity\Blog, MyBlogAdminManageBundle:BlogAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Content, label: Blog}

    my_blog_admin_manage.admin.user:
        class: MyBlog\Admin\ManageBundle\Admin\UserAdmin
        arguments: [~, MyBlog\CoreBundle\Entity\User, MyBlogAdminManageBundle:UserAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Content, label: User}

    my_blog_admin_manage.admin.like:
        class: MyBlog\Admin\ManageBundle\Admin\LikeAdmin
        arguments: [~, MyBlog\CoreBundle\Entity\Like, MyBlogAdminManageBundle:LikeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Content, label: Like}

    my_blog_admin_manage.admin.comment:
        class: MyBlog\Admin\ManageBundle\Admin\CommentAdmin
        arguments: [~, MyBlog\CoreBundle\Entity\Comment, MyBlogAdminManageBundle:CommentAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Content, label: Comment}

    my_blog_admin_manage.admin.user_basic_info:
        class: MyBlog\Admin\ManageBundle\Admin\UserBasicInfoAdmin
        arguments: [~, MyBlog\CoreBundle\Entity\UserBasicInfo, MyBlogAdminManageBundle:UserBasicInfoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Content, label: User Basic Info}
