parameters:
#    my_blog_core.example.class: MyBlog\CoreBundle\Example

services:
#    my_blog_core.example:
#        class: %my_blog_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
