<?php

namespace MyBlog\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserBasicInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBasicInfoRepository extends EntityRepository
{
}
